const fs = require('fs');
let content = fs.readFileSync('src/components/PrintModal.tsx', 'utf8');

// 1. Add new state variables
content = content.replace(
  "  const [userDetails, setUserDetails] = useState({",
  "  const [filterPeriod, setFilterPeriod] = useState<'month' | 'all'>('month');\n  const [filterType, setFilterType] = useState<'all' | 'income' | 'expense'>('all');\n  const [userDetails, setUserDetails] = useState({"
);

// 2. Replace monthEntries logic with filteredEntries logic
content = content.replace(
  "  const monthEntries = entries\n    .filter((e) => e.date.startsWith(monthKey))\n    .sort((a, b) => a.date.localeCompare(b.date));\n\n  const totalInc = monthEntries.filter((e) => e.type === 'income').reduce((s, e) => s + e.amount, 0);\n  const totalExp = monthEntries.filter((e) => e.type === 'expense').reduce((s, e) => s + e.amount, 0);",
  "  const filteredEntries = entries\n    .filter((e) => {\n      const matchPeriod = filterPeriod === 'all' ? true : e.date.startsWith(monthKey);\n      const matchType = filterType === 'all' ? true : e.type === filterType;\n      return matchPeriod && matchType;\n    })\n    .sort((a, b) => a.date.localeCompare(b.date));\n\n  const reportPeriodLabel = filterPeriod === 'all' ? 'All Time (Full Record)' : monthLabel;\n  const reportTypeLabel = filterType === 'all' ? 'Income & Expense' : filterType === 'income' ? 'Income Only' : 'Expense Only';\n\n  const totalInc = filteredEntries.filter((e) => e.type === 'income').reduce((s, e) => s + e.amount, 0);\n  const totalExp = filteredEntries.filter((e) => e.type === 'expense').reduce((s, e) => s + e.amount, 0);"
);

// 3. Replace all "monthEntries" with "filteredEntries"
content = content.replace(/monthEntries/g, 'filteredEntries');

// 4. Update the HTML generator string to use the new labels and remove watermarks/hasvolt details
// Replace statement period label
content = content.replace(
  "<span>Statement Period: <strong>${monthLabel}</strong></span>",
  "<span>Statement Period: <strong>${reportPeriodLabel}</strong><br/><span style=\"font-size:10px; color:#64748b;\">Type: ${reportTypeLabel}</span></span>"
);

// Remove watermark CSS
content = content.replace(
  "    .watermark-bg { position: fixed; top: 48%; left: 50%; transform: translate(-50%, -50%) rotate(-28deg); font-size: 42px; font-weight: 900; color: rgba(15, 23, 42, 0.035); letter-spacing: 3px; pointer-events: none; z-index: 0; text-align: center; line-height: 1.35; user-select: none; }\n",
  ""
);

// Remove watermark HTML
content = content.replace(
  "  <div class=\"watermark-bg\">\n    Daily Khata Pro<br/>Financial Record\n  </div>\n",
  ""
);

// Change footer
content = content.replace(
  "  <div class=\"developer-colophon-box\" style=\"justify-content: space-between;\">\n    <div>\n      <div style=\"font-weight: 700; color: #0f172a; font-size: 10px;\">Generated by Daily Khata Pro</div>\n      <div style=\"font-size: 9px; color: #64748b; margin-top: 2px;\">www.rozfiber.com</div>\n    </div>\n    <div style=\"text-align: right; border-left: 1px solid #e2e8f0; padding-left: 16px;\">\n      <div style=\"font-family: monospace; font-size: 10px; font-weight: 700; color: #0f172a; letter-spacing: 0.5px;\">POWERED BY HASVOLT</div>\n      <div style=\"font-size: 9px; color: #64748b; margin-top: 2px;\">www.hasvolt.com</div>\n    </div>\n  </div>",
  "  <div class=\"developer-colophon-box\" style=\"justify-content: space-between;\">\n    <div>\n      <div style=\"font-weight: 700; color: #0f172a; font-size: 10px;\">Generated by Daily Khata Pro</div>\n      <div style=\"font-size: 9px; color: #64748b; margin-top: 2px;\">www.rozfiber.com</div>\n    </div>\n  </div>"
);

// 5. Add configuration UI
const uiConfigStr = `
          {/* Data Filter Options */}
          <div className="bg-[var(--theme-surface,#0E1A29)] border border-[var(--theme-border,#213E61)] rounded-xl p-4 no-print mb-4">
            <h3 className="text-[12px] font-bold text-[#F8FAFC] mb-3 uppercase tracking-wider">Report Configuration</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-[10px] font-bold text-[#94A3B8] uppercase mb-1">Time Period</label>
                <select 
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[#F8FAFC] focus:border-[#38BDF8] outline-none"
                  value={filterPeriod}
                  onChange={(e) => setFilterPeriod(e.target.value as 'month' | 'all')}
                >
                  <option value="month">Current Month ({monthLabel})</option>
                  <option value="all">All Time (Full Data)</option>
                </select>
              </div>
              <div>
                <label className="block text-[10px] font-bold text-[#94A3B8] uppercase mb-1">Transaction Type</label>
                <select 
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[#F8FAFC] focus:border-[#38BDF8] outline-none"
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value as 'all' | 'income' | 'expense')}
                >
                  <option value="all">Income & Expense</option>
                  <option value="income">Income Only</option>
                  <option value="expense">Expense Only</option>
                </select>
              </div>
            </div>
          </div>
`;

content = content.replace(
  "          {/* User Details Optional Input */}",
  uiConfigStr + "\n          {/* User Details Optional Input */}"
);

// Update UI labels to use reportPeriodLabel
content = content.replace(
  "{monthLabel} · Daily Khata Pro Statement",
  "{reportPeriodLabel} · Daily Khata Pro Statement"
);
content = content.replace(
  "Period: <strong className=\"text-[#F8FAFC]\">{monthLabel}</strong>",
  "Period: <strong className=\"text-[#F8FAFC]\">{reportPeriodLabel}</strong>"
);
content = content.replace(
  "<div class=\"sec-title\">Monthly Transactions Log (${monthLabel} · ${filteredEntries.length} Records)</div>",
  "<div class=\"sec-title\">Transaction Log (${reportPeriodLabel} · ${filteredEntries.length} Records)</div>"
);
content = content.replace(
  "All Monthly Transactions Log",
  "All Transactions Log"
);
content = content.replace(
  "Recent Monthly Entries",
  "Recent Entries"
);

fs.writeFileSync('src/components/PrintModal.tsx', content, 'utf8');
