import React, { useState } from 'react';
import { Entry, FundType } from '../types';
import { FUND_ORDER, FUND_LABELS } from '../data/defaults';
import { formatCurrency, calculateFundTotals, downloadCSVReport } from '../utils/khataCalculations';
import { X, Printer, Download, FileText, Zap, FileSpreadsheet, Eye, ListOrdered } from 'lucide-react';

interface PrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  entries: Entry[];
  targetMonth: Date;
}

export const PrintModal: React.FC<PrintModalProps> = ({
  isOpen,
  onClose,
  entries,
  targetMonth
}) => {
  const [viewMode, setViewMode] = useState<'preview' | 'itemized'>('preview');
  const [filterPeriod, setFilterPeriod] = useState<'month' | 'all'>('month');
  const [filterType, setFilterType] = useState<'all' | 'income' | 'expense'>('all');
  const [userDetails, setUserDetails] = useState({
    name: '',
    contact: '',
    clientName: '',
    taxId: '',
    note: ''
  });

  if (!isOpen) return null;

  const escapeHtml = (str: string) => {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  };

  const fundTotals = calculateFundTotals(entries);
  const monthKey = `${targetMonth.getFullYear()}-${String(targetMonth.getMonth() + 1).padStart(2, '0')}`;
  const monthLabel = targetMonth.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });

  const filteredEntries = entries
    .filter((e) => {
      const matchPeriod = filterPeriod === 'all' ? true : e.date.startsWith(monthKey);
      const matchType = filterType === 'all' ? true : e.type === filterType;
      return matchPeriod && matchType;
    })
    .sort((a, b) => a.date.localeCompare(b.date));

  const reportPeriodLabel = filterPeriod === 'all' ? 'All Time (Full Record)' : monthLabel;
  const reportTypeLabel = filterType === 'all' ? 'Income & Expense' : filterType === 'income' ? 'Income Only' : 'Expense Only';

  const totalInc = filteredEntries.filter((e) => e.type === 'income').reduce((s, e) => s + e.amount, 0);
  const totalExp = filteredEntries.filter((e) => e.type === 'expense').reduce((s, e) => s + e.amount, 0);
  const netSaved = totalInc - totalExp;
  const grandTotal = Object.values(fundTotals).reduce((sum, v) => sum + v, 0);

  // Generate the clean standalone Printable Document HTML
  const generateStatementBodyContent = () => {
    return `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; color: #0f172a; line-height: 1.45; background: #fff; max-width: 820px; margin: 0 auto; padding: 12px 16px;">
        <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #0284C7; padding-bottom: 12px; margin-bottom: 16px;">
          <div>
            <div style="font-size: 20px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px;">Daily Khata Pro — Income &amp; Expense Statement</div>
            <div style="font-size: 11px; color: #64748b; margin-top: 2px;">Smart Fund Systematic Money Record &amp; Wealth Audit</div>
          </div>
          <div style="text-align: right; font-size: 11px; color: #475569;">
            <div style="font-weight: 700; color: #0f172a;">Financial Report</div>
            <div style="color: #64748b;">Daily Khata Pro Statement</div>
          </div>
        </div>

        <div style="font-size: 11.5px; color: #475569; display: flex; justify-content: space-between; background: #f8fafc; padding: 10px 14px; border-radius: 6px; margin-bottom: 18px; border: 1px solid #e2e8f0;">
          <span>Statement Period: <strong style="color: #0f172a;">${reportPeriodLabel}</strong><br/><span style="font-size:10px; color:#64748b;">Type: ${reportTypeLabel}</span></span>
          <span>Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
        </div>

        ${(userDetails.name || userDetails.contact || userDetails.clientName || userDetails.taxId || userDetails.note) ? `
        <div style="border-left: 3px solid #0284C7; background: #f0f9ff; padding: 12px 14px; border-radius: 4px; margin-bottom: 18px; font-size: 11px; color: #0f172a;">
          <div style="display: flex; justify-content: space-between; gap: 16px;">
            <div style="flex: 1;">
              <div style="color: #64748b; font-size: 9px; font-weight: 700; text-transform: uppercase; margin-bottom: 2px;">From / Generated By</div>
              ${userDetails.name ? `<div><strong style="color: #0284C7; font-size: 12px;">${escapeHtml(userDetails.name)}</strong></div>` : '<div>-</div>'}
              ${userDetails.contact ? `<div>${escapeHtml(userDetails.contact)}</div>` : ''}
            </div>
            <div style="flex: 1; border-left: 1px solid #cbd5e1; padding-left: 16px;">
              <div style="color: #64748b; font-size: 9px; font-weight: 700; text-transform: uppercase; margin-bottom: 2px;">To / Client Details</div>
              ${userDetails.clientName ? `<div><strong style="color: #0f172a; font-size: 12px;">${escapeHtml(userDetails.clientName)}</strong></div>` : '<div>-</div>'}
              ${userDetails.taxId ? `<div><span style="color: #475569;">Tax/GST ID:</span> ${escapeHtml(userDetails.taxId)}</div>` : ''}
            </div>
          </div>
          ${userDetails.note ? `<div style="color: #475569; margin-top: 6px; padding-top: 6px; border-top: 1px dashed #cbd5e1;"><strong>Note:</strong> ${escapeHtml(userDetails.note)}</div>` : ''}
        </div>
        ` : ''}

        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; background: #0f172a; color: #fff; padding: 14px; border-radius: 8px; margin-bottom: 20px; text-align: center;">
          <div>
            <div style="font-size: 10px; text-transform: uppercase; color: #94a3b8; font-weight: 700; letter-spacing: 0.5px;">Total Income</div>
            <div style="font-size: 18px; font-weight: bold; margin-top: 4px; color: #34d399; font-family: monospace;">+${formatCurrency(totalInc, false, false)}</div>
          </div>
          <div>
            <div style="font-size: 10px; text-transform: uppercase; color: #94a3b8; font-weight: 700; letter-spacing: 0.5px;">Total Expense</div>
            <div style="font-size: 18px; font-weight: bold; margin-top: 4px; color: #f87171; font-family: monospace;">-${formatCurrency(totalExp, false, false)}</div>
          </div>
          <div>
            <div style="font-size: 10px; text-transform: uppercase; color: #94a3b8; font-weight: 700; letter-spacing: 0.5px;">Net Savings / Surplus</div>
            <div style="font-size: 18px; font-weight: bold; margin-top: 4px; color: ${netSaved >= 0 ? '#34d399' : '#f87171'}; font-family: monospace;">${netSaved >= 0 ? '+' : ''}${formatCurrency(netSaved, false, false)}</div>
          </div>
        </div>

        <div style="font-size: 12px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px; color: #1e293b; border-bottom: 1.5px solid #cbd5e1; padding-bottom: 5px; margin-top: 18px; margin-bottom: 8px;">Smart Fund Balances (Current Position)</div>
        <table style="width: 100%; border-collapse: collapse; font-size: 11px; margin-bottom: 16px;">
          <thead>
            <tr>
              <th style="text-align: left; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Fund Pot</th>
              <th style="text-align: right; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Current Balance</th>
            </tr>
          </thead>
          <tbody>
            ${FUND_ORDER.map(
              (f) => `
              <tr>
                <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0;"><strong>${FUND_LABELS[f]}</strong></td>
                <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0; text-align: right; font-family: monospace; font-size: 12px; font-weight: 700;">${formatCurrency(fundTotals[f], false, false)}</td>
              </tr>
            `
            ).join('')}
            <tr style="font-weight: bold; background: #f8fafc; border-top: 2px solid #0f172a;">
              <td style="padding: 6px 8px;">Grand Total Combined</td>
              <td style="padding: 6px 8px; text-align: right; font-family: monospace; font-size: 13px; color: #0f172a;">${formatCurrency(grandTotal, false, false)}</td>
            </tr>
          </tbody>
        </table>

        <div style="font-size: 12px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px; color: #1e293b; border-bottom: 1.5px solid #cbd5e1; padding-bottom: 5px; margin-top: 18px; margin-bottom: 8px;">Transaction Log (${reportPeriodLabel} · ${filteredEntries.length} Records)</div>
        <table style="width: 100%; border-collapse: collapse; font-size: 11px; margin-bottom: 16px;">
          <thead>
            <tr>
              <th style="text-align: left; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Date</th>
              <th style="text-align: left; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Type</th>
              <th style="text-align: left; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Category / Source</th>
              <th style="text-align: left; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Fund Pot</th>
              <th style="text-align: left; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Note</th>
              <th style="text-align: right; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; color: #475569; font-weight: 700; background: #f1f5f9;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${
              filteredEntries.length === 0
                ? `<tr><td colspan="6" style="text-align: center; color: #94a3b8; padding: 16px;">No entries logged for this period.</td></tr>`
                : filteredEntries
                    .map(
                      (e) => `
                <tr>
                  <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0; font-family: monospace;">${e.date}</td>
                  <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0;">
                    <span style="display: inline-block; padding: 2px 6px; font-size: 9.5px; font-weight: 700; border-radius: 4px; text-transform: uppercase; background: ${e.type === 'income' ? '#dcfce7' : '#fee2e2'}; color: ${e.type === 'income' ? '#166534' : '#991b1b'};">
                      ${e.type.toUpperCase()}
                    </span>
                  </td>
                  <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0;"><strong>${e.type === 'income' ? (e.source || 'Daily Income') : (e.category || 'Expense')}</strong></td>
                  <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0; color: #475569;">${e.type === 'income' ? 'Smart Fund Split' : FUND_LABELS[e.fund || 'personal']}</td>
                  <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0; color: #64748b; font-size: 10.5px;">${e.note || '-'}</td>
                  <td style="padding: 6px 8px; border-bottom: 1px solid #e2e8f0; text-align: right; font-family: monospace; font-size: 12px; font-weight: 700; color: ${e.type === 'income' ? '#166534' : '#991b1b'}; white-space: nowrap;">
                    ${e.type === 'income' ? '+' : '-'}${formatCurrency(e.amount, false, false)}
                  </td>
                </tr>
              `
                    )
                    .join('')
            }
          </tbody>
        </table>

        <div style="margin-top: 24px; padding-top: 8px; border-top: 1.5px solid #e2e8f0; font-size: 10px; color: #64748b; display: flex; justify-content: space-between; align-items: center;">
          <span>• End of Financial Report •</span>
          <span>Daily Khata Pro Statement</span>
        </div>

        <div style="margin-top: 14px; padding: 10px 14px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #64748b; page-break-inside: avoid;">
          <div>
            <div style="font-weight: 700; color: #0f172a; font-size: 10.5px;">Generated By Daily Khata Pro</div>
            <div style="font-size: 9px; color: #64748b; margin-top: 2px;">www.rozfiber.com</div>
          </div>
          <div style="text-align: right; font-size: 9px; color: #94a3b8;">
            Audit-Grade Financial Record
          </div>
        </div>
      </div>
    `;
  };

  const generateStatementHTML = () => {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Daily Khata Pro — Financial Statement (${monthLabel})</title>
  <style>
    @page { size: A4 portrait; margin: 10mm 12mm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; padding: 16px; color: #0f172a; max-width: 820px; margin: 0 auto; line-height: 1.45; background: #fff; }
    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  ${generateStatementBodyContent()}
</body>
</html>`;
  };

  // Direct native browser printing with immediate PDF support
  const handlePrint = () => {
    window.print();
  };

  // Download standalone printable HTML report
  const handleDownloadHTML = () => {
    const htmlContent = generateStatementHTML();
    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `DailyKhata-Statement-${monthLabel.replace(/\s+/g, '-')}.html`);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  const handleDownloadCSV = () => {
    downloadCSVReport(entries, targetMonth);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/80 backdrop-blur-xs animate-in fade-in duration-150 print:p-0 print:bg-white print:static print:inset-auto print:z-auto print:block">
      <div className="print:hidden bg-[var(--theme-surface,#0E1A29)] border border-[var(--theme-border,#213E61)] rounded-2xl w-full max-w-2xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden text-left">
        {/* Modal Header */}
        <div className="px-5 py-4 border-b border-[var(--theme-border,#213E61)] flex items-center justify-between bg-[var(--theme-surface,#0E1A29)]">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] flex items-center justify-center text-[#FFC700]">
              <FileText className="w-4.5 h-4.5" />
            </div>
            <div>
              <h2 className="font-serif-display text-[16px] font-bold text-[var(--theme-text,#F8FAFC)]">
                Financial Statement Preview
              </h2>
              <p className="text-[11px] text-[var(--theme-text-dim,#94A3B8)]">
                {reportPeriodLabel} · Daily Khata Pro Statement
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-[var(--theme-text-dim,#94A3B8)] hover:text-[var(--theme-text,#F8FAFC)] hover:bg-black/5 dark:hover:bg-white/5 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* View Toggle Bar */}
        <div className="px-5 py-2.5 bg-[var(--theme-bg,#070E18)] border-b border-[var(--theme-border,#213E61)] flex items-center justify-between">
          <div className="flex gap-1.5 bg-[var(--theme-surface,#0E1A29)] p-1 rounded-xl border border-[var(--theme-border,#213E61)]">
            <button
              onClick={() => setViewMode('preview')}
              className={`px-3 py-1 rounded-lg text-[11.5px] font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                viewMode === 'preview'
                  ? 'bg-[#FFC700] text-[#0B1017] shadow-xs'
                  : 'text-[var(--theme-text-dim,#94A3B8)] hover:text-[var(--theme-text,#F8FAFC)]'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Summary View</span>
            </button>
            <button
              onClick={() => setViewMode('itemized')}
              className={`px-3 py-1 rounded-lg text-[11.5px] font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                viewMode === 'itemized'
                  ? 'bg-[#FFC700] text-[#0B1017] shadow-xs'
                  : 'text-[var(--theme-text-dim,#94A3B8)] hover:text-[var(--theme-text,#F8FAFC)]'
              }`}
            >
              <ListOrdered className="w-3.5 h-3.5" />
              <span>All Transactions ({filteredEntries.length})</span>
            </button>
          </div>

          <span className="text-[11px] text-[var(--theme-text-dim,#94A3B8)] hidden sm:inline">
            A4 Ready Printable Document
          </span>
        </div>

        {/* Modal Body Preview */}
        <div className="p-5 sm:p-6 overflow-y-auto space-y-5 bg-[var(--theme-bg,#070E18)] text-[var(--theme-text,#F8FAFC)] text-[13px] leading-relaxed flex-1 max-h-[calc(92vh-180px)]">

          {/* Data Filter Options */}
          <div className="bg-[var(--theme-surface,#0E1A29)] border border-[var(--theme-border,#213E61)] rounded-xl p-4 no-print mb-4">
            <h3 className="text-[12px] font-bold text-[var(--theme-text,#F8FAFC)] mb-3 uppercase tracking-wider">Report Configuration</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-[10px] font-bold text-[var(--theme-text-dim,#94A3B8)] uppercase mb-1">Time Period</label>
                <select 
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none"
                  value={filterPeriod}
                  onChange={(e) => setFilterPeriod(e.target.value as 'month' | 'all')}
                >
                  <option value="month">Current Month ({monthLabel})</option>
                  <option value="all">All Time (Full Data)</option>
                </select>
              </div>
              <div>
                <label className="block text-[10px] font-bold text-[var(--theme-text-dim,#94A3B8)] uppercase mb-1">Transaction Type</label>
                <select 
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none"
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value as 'all' | 'income' | 'expense')}
                >
                  <option value="all">Income & Expense</option>
                  <option value="income">Income Only</option>
                  <option value="expense">Expense Only</option>
                </select>
              </div>
            </div>
          </div>

          {/* User Details Optional Input */}
          <div className="bg-[var(--theme-surface,#0E1A29)] border border-[var(--theme-border,#213E61)] rounded-xl p-4 no-print">
            <h3 className="text-[12px] font-bold text-[var(--theme-text,#F8FAFC)] mb-3 uppercase tracking-wider">Add Details to Print Report (Optional)</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="space-y-3">
                <div className="text-[10px] font-bold text-[var(--theme-text-dim,#94A3B8)] uppercase">From (Your Details)</div>
                <input 
                  type="text" 
                  placeholder="Your Name or Business Name"
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none"
                  value={userDetails.name}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, name: e.target.value }))}
                />
                <input 
                  type="text" 
                  placeholder="Your Phone or Email"
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none"
                  value={userDetails.contact}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, contact: e.target.value }))}
                />
              </div>
              <div className="space-y-3">
                <div className="text-[10px] font-bold text-[var(--theme-text-dim,#94A3B8)] uppercase">To (Client Details)</div>
                <input 
                  type="text" 
                  placeholder="Client Name or Business"
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none"
                  value={userDetails.clientName}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, clientName: e.target.value }))}
                />
                <input 
                  type="text" 
                  placeholder="Client Tax ID / GST No."
                  className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none"
                  value={userDetails.taxId}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, taxId: e.target.value }))}
                />
              </div>
              <input 
                type="text" 
                placeholder="Additional Address or Note (Optional)"
                className="w-full bg-[var(--theme-bg,#070E18)] border border-[var(--theme-border,#213E61)] rounded-lg px-3 py-2 text-[12px] text-[var(--theme-text,#F8FAFC)] focus:border-[#38BDF8] outline-none sm:col-span-2"
                value={userDetails.note}
                onChange={(e) => setUserDetails(prev => ({ ...prev, note: e.target.value }))}
              />
            </div>
          </div>

          {/* Statement Banner Header */}
          <div className="border-b-2 border-[#FFC700] pb-3 flex justify-between items-start gap-4">
            <div>
              <div className="font-serif-display text-[20px] font-bold text-[var(--theme-text,#F8FAFC)] flex items-center gap-2">
                <Zap className="w-5 h-5 text-[#FFC700]" />
                <span>Daily Khata Pro Record</span>
              </div>
              <div className="text-[11px] text-[var(--theme-text-dim,#94A3B8)]">
                Smart Fund Systematic Financial Record
              </div>
            </div>
            <div className="text-right text-[11px] text-[var(--theme-text-dim,#94A3B8)]">
              <div>Period: <strong className="text-[var(--theme-text,#F8FAFC)]">{reportPeriodLabel}</strong></div>
              <div>Generated: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</div>
            </div>
          </div>

          {/* 3 Metric Cards */}
          <div className="grid grid-cols-3 gap-2.5">
            <div className="bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] rounded-xl p-3 text-center">
              <div className="text-[10.5px] uppercase tracking-wider text-[var(--theme-text-dim,#94A3B8)] font-bold">Total Income</div>
              <div className="font-serif-display text-[16px] sm:text-[18px] font-bold text-[#10B981] mt-0.5">
                +{formatCurrency(totalInc)}
              </div>
            </div>
            <div className="bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] rounded-xl p-3 text-center">
              <div className="text-[10.5px] uppercase tracking-wider text-[var(--theme-text-dim,#94A3B8)] font-bold">Total Expense</div>
              <div className="font-serif-display text-[16px] sm:text-[18px] font-bold text-[#EF4444] mt-0.5">
                -{formatCurrency(totalExp)}
              </div>
            </div>
            <div className="bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] rounded-xl p-3 text-center">
              <div className="text-[10.5px] uppercase tracking-wider text-[var(--theme-text-dim,#94A3B8)] font-bold">Net Saved</div>
              <div className="font-serif-display text-[16px] sm:text-[18px] font-bold text-[#FFC700] mt-0.5">
                {formatCurrency(netSaved)}
              </div>
            </div>
          </div>

          {viewMode === 'preview' ? (
            <>
              {/* Fund Balances */}
              <div className="space-y-2">
                <div className="text-[11px] uppercase tracking-wider font-bold text-[var(--theme-text-dim,#94A3B8)] border-b border-[var(--theme-border,#213E61)] pb-1">
                  Active 6-Fund Balances (All-Time)
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {FUND_ORDER.map((f) => (
                    <div key={f} className="p-2.5 rounded-xl bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] flex justify-between items-center text-[12px]">
                      <span className="text-[var(--theme-text-dim,#94A3B8)]">{FUND_LABELS[f]}</span>
                      <span className="font-mono font-bold text-[var(--theme-text,#F8FAFC)]">{formatCurrency(fundTotals[f])}</span>
                    </div>
                  ))}
                </div>
                <div className="flex justify-between items-center bg-[var(--theme-surface,#0E1A29)] border border-[#FFC700]/40 rounded-xl px-3.5 py-2 text-[13px] font-bold">
                  <span>Grand Total Combined Wealth</span>
                  <span className="font-serif-display text-[16px] text-[#FFC700] font-bold">
                    {formatCurrency(grandTotal)}
                  </span>
                </div>
              </div>

              {/* Quick Transaction List preview */}
              <div className="space-y-2">
                <div className="flex items-center justify-between text-[11px] uppercase tracking-wider font-bold text-[var(--theme-text-dim,#94A3B8)] border-b border-[var(--theme-border,#213E61)] pb-1">
                  <span>Recent Entries ({filteredEntries.length})</span>
                  <button
                    onClick={() => setViewMode('itemized')}
                    className="text-[#FFC700] hover:underline normal-case font-medium cursor-pointer"
                  >
                    View All {filteredEntries.length} records →
                  </button>
                </div>
                {filteredEntries.slice(0, 5).map((e) => (
                  <div
                    key={e.id}
                    className="p-2.5 rounded-xl bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] flex items-center justify-between text-[12px]"
                  >
                    <div className="flex items-center gap-2">
                      <span
                        className={`w-2 h-2 rounded-full ${
                          e.type === 'income' ? 'bg-[#10B981]' : 'bg-[#EF4444]'
                        }`}
                      />
                      <span className="font-mono text-[var(--theme-text-dim,#94A3B8)] text-[11px]">{e.date}</span>
                      <span className="font-semibold text-[var(--theme-text,#F8FAFC)]">
                        {e.type === 'income' ? (e.source || 'Daily Income') : (e.category || 'Expense')}
                      </span>
                    </div>
                    <span
                      className={`font-mono font-bold ${
                        e.type === 'income' ? 'text-[#10B981]' : 'text-[#EF4444]'
                      }`}
                    >
                      {e.type === 'income' ? '+' : '-'}{formatCurrency(e.amount)}
                    </span>
                  </div>
                ))}
              </div>
            </>
          ) : (
            /* Itemized Full Transactions Table */
            <div className="space-y-2">
              <div className="text-[11px] uppercase tracking-wider font-bold text-[var(--theme-text-dim,#94A3B8)] border-b border-[var(--theme-border,#213E61)] pb-1">
                All Transactions Log ({filteredEntries.length} Entries)
              </div>
              {filteredEntries.length === 0 ? (
                <div className="text-center py-6 text-[var(--theme-text-dim,#94A3B8)] text-[12px]">
                  No entries logged for this month yet.
                </div>
              ) : (
                <div className="space-y-1.5">
                  {filteredEntries.map((e) => (
                    <div
                      key={e.id}
                      className="p-2.5 rounded-xl bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] flex items-center justify-between text-[12px]"
                    >
                      <div className="space-y-0.5">
                        <div className="flex items-center gap-2">
                          <span
                            className={`px-1.5 py-0.5 rounded text-[9.5px] font-extrabold uppercase ${
                              e.type === 'income'
                                ? 'bg-[#10B981]/20 text-[#10B981]'
                                : 'bg-[#EF4444]/20 text-[#EF4444]'
                            }`}
                          >
                            {e.type}
                          </span>
                          <span className="font-mono text-[var(--theme-text-dim,#94A3B8)] text-[11px]">{e.date}</span>
                          <span className="font-semibold text-[var(--theme-text,#F8FAFC)]">
                            {e.type === 'income' ? (e.source || 'Income') : (e.category || 'Expense')}
                          </span>
                        </div>
                        {e.note && <p className="text-[11px] text-[var(--theme-text-dim,#94A3B8)] pl-1">{e.note}</p>}
                      </div>
                      <span
                        className={`font-mono font-bold text-[13px] ${
                          e.type === 'income' ? 'text-[#10B981]' : 'text-[#EF4444]'
                        }`}
                      >
                        {e.type === 'income' ? '+' : '-'}{formatCurrency(e.amount)}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Modal Footer Controls */}
        <div className="px-5 py-3.5 border-t border-[var(--theme-border,#213E61)] bg-[var(--theme-surface,#0E1A29)] flex flex-wrap items-center justify-between gap-2.5">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl border border-[var(--theme-border,#213E61)] bg-transparent text-[var(--theme-text-dim,#94A3B8)] hover:text-[var(--theme-text,#F8FAFC)] font-semibold text-[13px] cursor-pointer"
          >
            Close
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadCSV}
              className="px-3.5 py-2 rounded-xl bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] text-[var(--theme-text,#F8FAFC)] hover:text-[var(--theme-primary,#38BDF8)] font-bold text-[12.5px] flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <FileSpreadsheet className="w-4 h-4 text-[var(--theme-primary,#38BDF8)]" />
              <span className="hidden sm:inline">Export</span> CSV
            </button>

            <button
              onClick={handleDownloadHTML}
              className="px-3.5 py-2 rounded-xl bg-[var(--theme-card,#132438)] border border-[var(--theme-border,#213E61)] text-[var(--theme-text,#F8FAFC)] hover:text-[#FFC700] font-bold text-[12.5px] flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <Download className="w-4 h-4" />
              <span>Download HTML</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-4.5 py-2 rounded-xl bg-[#FFC700] hover:bg-[#FFD233] text-[#0B1017] font-bold text-[13px] flex items-center gap-1.5 cursor-pointer transition-all shadow-md active:scale-95"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Save PDF</span>
            </button>
          </div>
        </div>
      </div>

      {/* Real Printable DOM Document */}
      <div
        id="daily-khata-printable-statement"
        className="hidden print:block w-full max-w-full bg-white text-slate-900"
        dangerouslySetInnerHTML={{ __html: generateStatementBodyContent() }}
      />
    </div>
  );
};
