import { AppLanguage, FundType, PaymentMode, WorkStatus, MoodType } from '../types';

// ==========================================
// 1. CATEGORY & SOURCE LOCALIZATION MAPS
// ==========================================

export const CATEGORY_TRANSLATIONS: Record<string, Record<AppLanguage, string>> = {
  'Food & Dining': {
    en: 'Food & Dining',
    hi: 'भोजन एवं रेस्टोरेंट',
    hinglish: 'Khana & Dining',
    ur: 'کھانا اور ہوٹلنگ',
    bn: 'খাবার ও রেস্তোরাঁ',
    es: 'Comida y Restaurantes',
    ar: 'الطعام والمطاعم',
    fr: 'Alimentation & Restaurants',
    de: 'Essen & Gastronomie',
    ru: 'Еда и рестораны',
    pt: 'Alimentação e Restaurantes',
    id: 'Makanan & Kuliner',
    ja: '食費・外食',
    zh: '餐饮与美食'
  },
  'Groceries & Household': {
    en: 'Groceries & Household',
    hi: 'किराना एवं घरेलू सामान',
    hinglish: 'Ration & Household',
    ur: 'راشن اور گھریلو سامان',
    bn: 'মুদিখানা ও গৃহস্থালি',
    es: 'Supermercado y Hogar',
    ar: 'البقالة والمستلزمات المنزلية',
    fr: 'Courses & Maison',
    de: 'Lebensmittel & Haushalt',
    ru: 'Продукты и быт',
    pt: 'Mercado e Casa',
    id: 'Belanja Dapur & Rumah',
    ja: '食料品・日用品',
    zh: '日杂百货与食品'
  },
  'Rent & Housing': {
    en: 'Rent & Housing',
    hi: 'घर का किराया एवं आवास',
    hinglish: 'Ghar Kiraya & Rent',
    ur: 'مکان کا کرایہ اور رہائش',
    bn: 'বাড়ি ভাড়া ও বাসস্থান',
    es: 'Alquiler y Vivienda',
    ar: 'الإيجار والسكن',
    fr: 'Loyer & Logement',
    de: 'Miete & Wohnen',
    ru: 'Аренда и жилье',
    pt: 'Aluguel e Moradia',
    id: 'Sewa & Tempat Tinggal',
    ja: '家賃・住居費',
    zh: '房租与居住'
  },
  'Electricity & Utilities': {
    en: 'Electricity & Utilities',
    hi: 'बिजली बिल एवं उपयोगिताएं',
    hinglish: 'Bijli Bill & Utilities',
    ur: 'بجلی کا بل اور یوٹیلیٹیز',
    bn: 'বিদ্যুৎ বিল ও ইউটিলিটি',
    es: 'Electricidad y Servicios',
    ar: 'الكهرباء والمرافق',
    fr: 'Électricité & Factures',
    de: 'Strom & Nebenkosten',
    ru: 'Электричество и коммуналка',
    pt: 'Energia e Contas',
    id: 'Listrik & Tagihan',
    ja: '光熱費・水道代',
    zh: '水电与公共事业'
  },
  'Transport & Fuel': {
    en: 'Transport & Fuel',
    hi: 'यातायात एवं पेट्रोल/डीजल',
    hinglish: 'Transport & Petrol/Fuel',
    ur: 'ٹرانسپورٹ اور پیٹرول',
    bn: 'যাতায়াত ও জ্বালানি',
    es: 'Transporte y Combustible',
    ar: 'المواصلات والوقود',
    fr: 'Transports & Carburant',
    de: 'Transport & Treibstoff',
    ru: 'Транспорт и бензин',
    pt: 'Transporte e Combustível',
    id: 'Transportasi & Bensin',
    ja: '交通費・ガソリン代',
    zh: '交通与燃油'
  },
  'Mobile & Internet': {
    en: 'Mobile & Internet',
    hi: 'मोबाइल रिचार्ज एवं इंटरनेट',
    hinglish: 'Mobile Recharge & WiFi',
    ur: 'موبائل ریچارج اور انٹرنیٹ',
    bn: 'মোবাইল রিচার্জ ও ইন্টারনেট',
    es: 'Móvil e Internet',
    ar: 'الهاتف والإنترنت',
    fr: 'Téléphone & Internet',
    de: 'Mobilfunk & Internet',
    ru: 'Связь и интернет',
    pt: 'Celular e Internet',
    id: 'Pulsa & Internet',
    ja: '通信費・ネット代',
    zh: '通讯与网络'
  },
  'Health & Medicine': {
    en: 'Health & Medicine',
    hi: 'दवाइयां एवं स्वास्थ्य देखभाल',
    hinglish: 'Dawa & Healthcare',
    ur: 'ادویات اور علاج معالجہ',
    bn: 'ওষুধ ও স্বাস্থ্যসেবা',
    es: 'Salud y Farmacia',
    ar: 'الصحة والأدوية',
    fr: 'Santé & Médicaments',
    de: 'Gesundheit & Medizin',
    ru: 'Здоровье и лекарства',
    pt: 'Saúde e Medicamentos',
    id: 'Kesehatan & Obat',
    ja: '医療費・薬品代',
    zh: '医疗与健康'
  },
  'Education & Courses': {
    en: 'Education & Courses',
    hi: 'शिक्षा, किताबें एवं फीस',
    hinglish: 'Education & Study Fees',
    ur: 'تعلیم، فیس اور کورسز',
    bn: 'শিক্ষা, বই ও কোর্স ফি',
    es: 'Educación y Cursos',
    ar: 'التعليم والكتب',
    fr: 'Éducation & Formations',
    de: 'Bildung & Kurse',
    ru: 'Образование и курсы',
    pt: 'Educação e Cursos',
    id: 'Pendidikan & Kursus',
    ja: '教育・書籍代',
    zh: '教育与进修'
  },
  'Shopping & Clothing': {
    en: 'Shopping & Clothing',
    hi: 'कपड़े एवं सामान्य खरीदारी',
    hinglish: 'Kapde & Shopping',
    ur: 'شاپنگ اور ملبوسات',
    bn: 'পোশাক ও কেনাকাটা',
    es: 'Compras y Ropa',
    ar: 'التسوق والملابس',
    fr: 'Achats & Vêtements',
    de: 'Shopping & Kleidung',
    ru: 'Покупки и одежда',
    pt: 'Compras e Vestuário',
    id: 'Belanja & Pakaian',
    ja: '衣服・ショッピング',
    zh: '购物与服饰'
  },
  'Entertainment & Leisure': {
    en: 'Entertainment & Leisure',
    hi: 'मनोरंजन एवं ओटीटी/मूवीज',
    hinglish: 'Entertainment & Movies',
    ur: 'تفریح اور سیر و تفریح',
    bn: 'বিনোদন ও সিনেমা',
    es: 'Entretenimiento y Ocio',
    ar: 'الترفيه والتسلية',
    fr: 'Divertissement & Loisirs',
    de: 'Unterhaltung & Freizeit',
    ru: 'Развлечения и отдых',
    pt: 'Lazer e Entretenimento',
    id: 'Hiburan & Rekreasi',
    ja: '趣味・娯楽費',
    zh: '休闲与娱乐'
  },
  'Personal Care & Grooming': {
    en: 'Personal Care & Grooming',
    hi: 'सैलून एवं व्यक्तिगत देखभाल',
    hinglish: 'Salon & Self Care',
    ur: 'پرسنل کیئر اور سیلون',
    bn: 'সেলুন ও রূপচর্চা',
    es: 'Cuidado Personal y Salón',
    ar: 'العناية الشخصية',
    fr: 'Soins Personnels',
    de: 'Körperpflege & Salon',
    ru: 'Уход за собой и салон',
    pt: 'Cuidados Pessoais',
    id: 'Perawatan Diri & Salon',
    ja: '美容・理容費',
    zh: '个人护理与美容'
  },
  'Travel & Holidays': {
    en: 'Travel & Holidays',
    hi: 'यात्रा एवं छुट्टियां',
    hinglish: 'Travel & Vacation',
    ur: 'سفر اور چھٹیاں',
    bn: 'ভ্রমণ ও ছুটি',
    es: 'Viajes y Vacaciones',
    ar: 'السفر والإجازات',
    fr: 'Voyages & Vacances',
    de: 'Reisen & Urlaub',
    ru: 'Путешествия и отпуск',
    pt: 'Viagens e Férias',
    id: 'Perjalanan & Liburan',
    ja: '旅行・レジャー',
    zh: '旅游与度假'
  },
  'EMI & Debt Repayment': {
    en: 'EMI & Debt Repayment',
    hi: 'ईएमआई, कर्ज एवं ऋण भुगतान',
    hinglish: 'EMI & Loan Repayment',
    ur: 'قسط (EMI) اور قرض کی ادائیگی',
    bn: 'ইএমআই ও ঋণ পরিশোধ',
    es: 'Cuotas EMI y Préstamos',
    ar: 'الأقساط وسداد الديون',
    fr: 'Crédit & Remboursements',
    de: 'Kredite & Raten',
    ru: 'Кредиты и рассрочка',
    pt: 'Empréstimos e Parcelas',
    id: 'Cicilan & Pembayaran Hutang',
    ja: 'ローン・借入返済',
    zh: '还贷与分期'
  },
  'Family & Children': {
    en: 'Family & Children',
    hi: 'परिवार, माता-पिता एवं बच्चे',
    hinglish: 'Family & Bachhon ka Kharcha',
    ur: 'خاندان، والدین اور بچے',
    bn: 'পরিবার ও সন্তানাদি',
    es: 'Familia e Hijos',
    ar: 'الأسرة والأطفال',
    fr: 'Famille & Enfants',
    de: 'Familie & Kinder',
    ru: 'Семья и дети',
    pt: 'Família e Filhos',
    id: 'Keluarga & Anak',
    ja: '家族・子供関連費',
    zh: '家庭与子女'
  },
  'Donation & Charity': {
    en: 'Donation & Charity',
    hi: 'दान, खैरात एवं मदद',
    hinglish: 'Daan & Charity',
    ur: 'صدقات، خیرات اور عطیہ',
    bn: 'দান ও সাহায্য',
    es: 'Donaciones y Caridad',
    ar: 'الصدقات والتبرعات',
    fr: 'Dons & Charité',
    de: 'Spenden & Wohltätigkeit',
    ru: 'Пожертвования и благотворительность',
    pt: 'Doações e Caridade',
    id: 'Sedekah & Donasi',
    ja: '寄付・お布施',
    zh: '慈善与捐款'
  },
  'Investment Deposit': {
    en: 'Investment Deposit',
    hi: 'निवेश एवं एसआईपी जमा',
    hinglish: 'Investment & Mutual Fund Deposit',
    ur: 'سرمایہ کاری میں جمع',
    bn: 'বিনিয়োগ ও সঞ্চয় জমা',
    es: 'Depósito de Inversión',
    ar: 'إيداع الاستثمار',
    fr: 'Dépôt d’Investissement',
    de: 'Investitionsanzahlung',
    ru: 'Вклад и инвестиции',
    pt: 'Aporte de Investimento',
    id: 'Setoran Investasi',
    ja: '投資・積立金',
    zh: '投资与理财存入'
  },
  'Taxes & Fees': {
    en: 'Taxes & Fees',
    hi: 'टैक्स, चालान एवं शुल्क',
    hinglish: 'Tax & Govt Fees',
    ur: 'ٹیکس اور قانونی فیس',
    bn: 'ট্যাক্স ও সরকারি ফি',
    es: 'Impuestos y Tasas',
    ar: 'الضرائب والرسوم',
    fr: 'Impôts & Taxes',
    de: 'Steuern & Gebühren',
    ru: 'Налоги и сборы',
    pt: 'Impostos e Taxas',
    id: 'Pajak & Biaya Layanan',
    ja: '税金・手数料',
    zh: '税费与手续费'
  },
  'Miscellaneous & Other': {
    en: 'Miscellaneous & Other',
    hi: 'अन्य फुटकर खर्चे',
    hinglish: 'Anya / Other Kharch',
    ur: 'دیگر متفرق اخراجات',
    bn: 'অন্যান্য বিবিধ খরচ',
    es: 'Otros Gastos Varios',
    ar: 'نفقات متنوعة أخرى',
    fr: 'Dépenses Diverses',
    de: 'Sonstige Ausgaben',
    ru: 'Прочие расходы',
    pt: 'Outros Diversos',
    id: 'Lain-lain',
    ja: 'その他雑費',
    zh: '其他杂项支出'
  },
  'Food & Groceries': {
    en: 'Food & Groceries',
    hi: 'भोजन एवं राशन',
    hinglish: 'Khana & Ration',
    ur: 'کھانا اور راشن',
    bn: 'খাবার ও মুদিখানা',
    es: 'Comida y Alimentos',
    ar: 'الطعام والبقالة',
    fr: 'Alimentation & Épicerie',
    de: 'Essen & Lebensmittel',
    ru: 'Еда и продукты',
    pt: 'Alimentação e Mercado',
    id: 'Makanan & Sembako',
    ja: '食料品・日用品',
    zh: '食品与杂货'
  },
  'Housing & Rent': {
    en: 'Housing & Rent',
    hi: 'घर एवं किराया',
    hinglish: 'Ghar Kiraya & Rent',
    ur: 'مکان اور کرایہ',
    bn: 'বাড়ি ও ভাড়া',
    es: 'Vivienda y Alquiler',
    ar: 'السكن والإيجار',
    fr: 'Logement & Loyer',
    de: 'Wohnen & Miete',
    ru: 'Жилье и аренда',
    pt: 'Moradia e Aluguel',
    id: 'Rumah & Sewa',
    ja: '住居費・家賃',
    zh: '住房与房租'
  },
  'Utilities & Electricity': {
    en: 'Utilities & Electricity',
    hi: 'बिजली एवं बिल',
    hinglish: 'Bijli Bill & Utilities',
    ur: 'بجلی اور یوٹیلیٹیز',
    bn: 'বিদ্যুৎ ও বিল',
    es: 'Servicios y Electricidad',
    ar: 'الكهرباء والمرافق',
    fr: 'Électricité & Factures',
    de: 'Strom & Nebenkosten',
    ru: 'Коммуналка и электричество',
    pt: 'Contas e Eletricidade',
    id: 'Listrik & Utilitas',
    ja: '水道光熱費・電気',
    zh: '水电气费'
  },
  'Shopping & Apparel': {
    en: 'Shopping & Apparel',
    hi: 'शॉपिंग एवं वस्त्र',
    hinglish: 'Kapde & Shopping',
    ur: 'شاپنگ اور ملبوسات',
    bn: 'কেনাকাটা ও পোশাক',
    es: 'Compras y Ropa',
    ar: 'التسوق والملابس',
    fr: 'Achats & Vêtements',
    de: 'Shopping & Kleidung',
    ru: 'Покупки и одежда',
    pt: 'Compras e Vestuário',
    id: 'Belanja & Pakaian',
    ja: '衣服・買い物',
    zh: '购物与服饰'
  },
  'Personal Care & Wellness': {
    en: 'Personal Care & Wellness',
    hi: 'पर्सनल केयर एवं सैलून',
    hinglish: 'Personal Care & Salon',
    ur: 'پرسنل کیئر اور سیلون',
    bn: 'ব্যক্তিগত যত্ন ও সেলুন',
    es: 'Cuidado Personal y Bienestar',
    ar: 'العناية الشخصية والصحة',
    fr: 'Soins Personnels & Bien-être',
    de: 'Körperpflege & Wellness',
    ru: 'Уход за собой и здоровье',
    pt: 'Cuidados Pessoais e Bem-estar',
    id: 'Perawatan Diri & Salon',
    ja: '美容・セルフケア',
    zh: '个人护理与健康'
  },
  'Family & Household': {
    en: 'Family & Household',
    hi: 'परिवार एवं गृहस्थी',
    hinglish: 'Ghar Parivar & Rashan',
    ur: 'خاندان اور گھریلو اخراجات',
    bn: 'পরিবার ও গৃহস্থালি',
    es: 'Familia y Hogar',
    ar: 'الأسرة والمنزل',
    fr: 'Famille & Maison',
    de: 'Familie & Haushalt',
    ru: 'Семья и дом',
    pt: 'Família e Casa',
    id: 'Keluarga & Rumah Tangga',
    ja: '家族・家庭費',
    zh: '家庭与居家'
  },
  'Health & Medical': {
    en: 'Health & Medical',
    hi: 'दवा, डॉक्टर व स्वास्थ्य',
    hinglish: 'Dawa & Hospital/Health',
    ur: 'ادویات اور علاج',
    bn: 'ওষুধ ও চিকিৎসা',
    es: 'Salud y Farmacia',
    ar: 'الصحة والطبابة',
    fr: 'Santé & Médical',
    de: 'Gesundheit & Medizin',
    ru: 'Здоровье и медицина',
    pt: 'Saúde e Farmácia',
    id: 'Kesehatan & Obat',
    ja: '医療費・薬品代',
    zh: '医疗与医药'
  },
  'Dining & Entertainment': {
    en: 'Dining & Entertainment',
    hi: 'रेस्टोरेंट, भोजन व मनोरंजन',
    hinglish: 'Khana, Dining & Movies',
    ur: 'ہوٹلنگ اور تفریح',
    bn: 'রেস্তোরাঁ ও বিনোদন',
    es: 'Restaurantes y Ocio',
    ar: 'المطاعم والترفيه',
    fr: 'Restaurants & Loisirs',
    de: 'Gastronomie & Unterhaltung',
    ru: 'Кафе и развлечения',
    pt: 'Restaurantes e Lazer',
    id: 'Restoran & Hiburan',
    ja: '外食・娯楽費',
    zh: '餐饮与休闲娱乐'
  },
  'Education & Upskilling': {
    en: 'Education & Upskilling',
    hi: 'शिक्षा, कोर्स व किताबें',
    hinglish: 'Padhai, Coaching & Courses',
    ur: 'تعلیم اور کورسز',
    bn: 'শিক্ষা ও কোর্স',
    es: 'Educación y Cursos',
    ar: 'التعليم والتطوير',
    fr: 'Éducation & Formation',
    de: 'Bildung & Kurse',
    ru: 'Обучение и курсы',
    pt: 'Educação e Cursos',
    id: 'Pendidikan & Pelatihan',
    ja: '教育・スキルアップ',
    zh: '教育与技能培训'
  },
  'EMI, Loans & Debt': {
    en: 'EMI, Loans & Debt',
    hi: 'ईएमआई, लोन व ऋण',
    hinglish: 'EMI, Loan & Karza',
    ur: 'قسط (EMI) اور قرض',
    bn: 'ইএমআই ও ঋণ',
    es: 'Cuotas EMI y Deudas',
    ar: 'الأقساط والديون',
    fr: 'Crédit, Prêts & Dettes',
    de: 'Kredite & Raten',
    ru: 'Кредиты и долги',
    pt: 'Empréstimos e Dívidas',
    id: 'Cicilan & Hutang',
    ja: 'ローン・借入返済',
    zh: '还贷与债务'
  },
  'Software & Subscriptions': {
    en: 'Software & Subscriptions',
    hi: 'सॉफ्टवेयर, ऐप्स व सब्सक्रिप्शन',
    hinglish: 'Apps, Software & Subscriptions',
    ur: 'سافٹ ویئر اور سبسکرپشن',
    bn: 'সফটওয়্যার ও সাবস্ক্রিপশন',
    es: 'Software y Suscripciones',
    ar: 'البرمجيات والاشتراكات',
    fr: 'Logiciels & Abonnements',
    de: 'Software & Abos',
    ru: 'Софт и подписки',
    pt: 'Softwares e Assinaturas',
    id: 'Software & Langganan',
    ja: 'ソフトウェア・サブスク',
    zh: '软件与会员订阅'
  },
  'Business & Office Expenses': {
    en: 'Business & Office Expenses',
    hi: 'व्यापार, दुकान व ऑफिस खर्च',
    hinglish: 'Business & Office Kharcha',
    ur: 'کاروبار اور دفتر کے اخراجات',
    bn: 'ব্যবসা ও অফিস খরচ',
    es: 'Gastos de Negocio y Oficina',
    ar: 'مصاريف الأعمال والمكتب',
    fr: 'Frais Professionnels & Bureau',
    de: 'Geschäfts- & Bürokosten',
    ru: 'Бизнес и офис',
    pt: 'Despesas de Empresa e Escritório',
    id: 'Biaya Usaha & Kantor',
    ja: '事業費・オフィス経費',
    zh: '商务与办公支出'
  },
  'General & Miscellaneous': {
    en: 'General & Miscellaneous',
    hi: 'सामान्य एवं विविध खर्च',
    hinglish: 'General & Extra Kharch',
    ur: 'عام اور متفرق اخراجات',
    bn: 'সাধারণ ও বিবিধ খরচ',
    es: 'General y Varios',
    ar: 'نفقات عامة ومتنوعة',
    fr: 'Général & Divers',
    de: 'Allgemeines & Verschiedenes',
    ru: 'Общие и разные расходы',
    pt: 'Geral e Diversos',
    id: 'Umum & Lain-lain',
    ja: '一般・雑費',
    zh: '常规与杂项'
  }
};

export const SOURCE_TRANSLATIONS: Record<string, Record<AppLanguage, string>> = {
  'Salary & Wages': {
    en: 'Salary & Wages',
    hi: 'मासिक वेतन एवं नौकरी आय',
    hinglish: 'Monthly Salary & Wages',
    ur: 'ماہانہ تنخواہ اور اجرت',
    bn: 'মাসিক বেতন ও মজুরি',
    es: 'Salario y Sueldo',
    ar: 'الراتب والأجور',
    fr: 'Salaire & Rémunération',
    de: 'Gehalt & Lohn',
    ru: 'Зарплата и оклад',
    pt: 'Salário e Vencimentos',
    id: 'Gaji & Upah',
    ja: '給与・賞与',
    zh: '工资与薪酬'
  },
  'Business Profits': {
    en: 'Business Profits',
    hi: 'दुकान एवं व्यापार मुनाफा',
    hinglish: 'Business & Dukan Profit',
    ur: 'کاروباری منافع اور آمدنی',
    bn: 'ব্যবসার লাভ ও আয়',
    es: 'Beneficios Comerciales',
    ar: 'أرباح الأعمال والتجارة',
    fr: 'Bénéfices Commerciaux',
    de: 'Geschäftsgewinne',
    ru: 'Прибыль от бизнеса',
    pt: 'Lucros do Negócio',
    id: 'Keuntungan Usaha',
    ja: '事業利益・売上',
    zh: '营业利润与营收'
  },
  'Freelance & Contracts': {
    en: 'Freelance & Contracts',
    hi: 'फ्रीलांसिंग एवं प्रोजेक्ट बिलिंग',
    hinglish: 'Freelancing & Client Projects',
    ur: 'فری لانسنگ اور پروجیکٹ بلنگ',
    bn: 'ফ্রিল্যান্সিং ও চুক্তিভিত্তিক আয়',
    es: 'Freelance y Contratos',
    ar: 'العمل الحر والمشاريع',
    fr: 'Freelance & Contrats',
    de: 'Freiberuflich & Verträge',
    ru: 'Фриланс и контракты',
    pt: 'Freelance e Contratos',
    id: 'Freelance & Proyek',
    ja: 'フリーランス・副業報酬',
    zh: '自由职业与项目合同'
  },
  'Rental & Lease': {
    en: 'Rental & Lease',
    hi: 'मकान/दुकान किराया आमदनी',
    hinglish: 'Kiraya / Rental Income',
    ur: 'کرایہ اور لیز کی آمدنی',
    bn: 'ভাড়া ও ইজারা আয়',
    es: 'Ingresos por Alquiler',
    ar: 'إيرادات الإيجار',
    fr: 'Revenus Locatifs',
    de: 'Mieteinnahmen & Pacht',
    ru: 'Доход от аренды',
    pt: 'Renda de Aluguel',
    id: 'Pendapatan Sewa Properti',
    ja: '不動産収入・賃貸料',
    zh: '租金与租赁收入'
  },
  'Investments & Returns': {
    en: 'Investments & Returns',
    hi: 'डिविडेंड, ब्याज एवं निवेश रिटर्न',
    hinglish: 'Mutual Fund / Stock Returns',
    ur: 'منافع اور سرمایہ کاری کا ریٹرن',
    bn: 'বিনিয়োগের লভ্যাংশ ও সুদ',
    es: 'Rendimientos e Inversiones',
    ar: 'عوائد الاستثمار والأرباح',
    fr: 'Rendements & Dividendes',
    de: 'Kapitalerträge & Zinsen',
    ru: 'Инвестиции и дивиденды',
    pt: 'Rendimentos de Investimento',
    id: 'Hasil Investasi & Bunga',
    ja: '投資配当・利息収入',
    zh: '投资分红与理财收益'
  },
  'Gift & Grants': {
    en: 'Gift & Grants',
    hi: 'उपहार, इनामी राशि एवं अनुदान',
    hinglish: 'Gift & Reward Paisa',
    ur: 'تحفہ، انعام اور امداد',
    bn: 'উপহার ও অনুদান',
    es: 'Regalos y Subvenciones',
    ar: 'الهدايا والمنح',
    fr: 'Cadeaux & Subventions',
    de: 'Geschenke & Zuschüsse',
    ru: 'Подарки и премии',
    pt: 'Presentes e Bonificações',
    id: 'Hadiah & Bonus',
    ja: '贈与・臨時収入',
    zh: '礼金与赠款'
  },
  'Other Income': {
    en: 'Other Income',
    hi: 'अन्य विविध आमदनी',
    hinglish: 'Anya / Other Kamai',
    ur: 'دیگر متفرق آمدنی',
    bn: 'অন্যান্য আয়',
    es: 'Otros Ingresos',
    ar: 'دخل إضافي آخر',
    fr: 'Autres Revenus',
    de: 'Sonstige Einnahmen',
    ru: 'Прочие доходы',
    pt: 'Outras Rendas',
    id: 'Pendapatan Lainnya',
    ja: 'その他収入',
    zh: '其他杂项收入'
  },
  'Business & Sales': {
    en: 'Business & Sales',
    hi: 'व्यापारिक बिक्री एवं दुकान कमाई',
    hinglish: 'Business & Dukan Bikri',
    ur: 'کاروباری سیلز اور آمدنی',
    bn: 'ব্যবসা ও বিক্রয় আয়',
    es: 'Ventas y Negocio',
    ar: 'المبيعات والتجارة',
    fr: 'Ventes & Entreprise',
    de: 'Umsätze & Verkauf',
    ru: 'Продажи и бизнес',
    pt: 'Vendas e Negócios',
    id: 'Penjualan & Bisnis',
    ja: '事業売上・商売',
    zh: '营业额与销售'
  },
  'Client Invoices': {
    en: 'Client Invoices',
    hi: 'क्लाइंट इनवॉइस व बिलिंग',
    hinglish: 'Client Invoices & Billing',
    ur: 'کلائنٹ انوائس اور بلنگ',
    bn: 'ক্লায়েন্ট ইনভয়েস ও বিলিং',
    es: 'Facturas de Clientes',
    ar: 'فواتير العملاء',
    fr: 'Factures Clients',
    de: 'Kundenrechnungen',
    ru: 'Счета клиентов',
    pt: 'Faturas de Clientes',
    id: 'Tagihan Klien',
    ja: 'クライアント請求書',
    zh: '客户结算与发票'
  },
  'Freelance & Consulting': {
    en: 'Freelance & Consulting',
    hi: 'फ्रीलांसिंग एवं कंसल्टेंसी',
    hinglish: 'Freelance & Projects',
    ur: 'فری لانس اور مشاورت',
    bn: 'ফ্রিল্যান্সিং ও পরামর্শ',
    es: 'Freelance y Consultoría',
    ar: 'العمل الحر والاستشارات',
    fr: 'Freelance & Conseil',
    de: 'Freiberuflich & Beratung',
    ru: 'Фриланс и консалтинг',
    pt: 'Freelance e Consultoria',
    id: 'Freelance & Konsultasi',
    ja: 'フリーランス・コンサル',
    zh: '自由职业与咨询'
  },
  'Rental Income': {
    en: 'Rental Income',
    hi: 'मकान / दुकान किराया आय',
    hinglish: 'Kiraya (Rent) Income',
    ur: 'کرایہ کی آمدنی',
    bn: 'ভাড়া থেকে আয়',
    es: 'Ingresos por Alquiler',
    ar: 'دخل الإيجار',
    fr: 'Revenus Locatifs',
    de: 'Mieteinnahmen',
    ru: 'Доход от аренды',
    pt: 'Renda de Aluguel',
    id: 'Pendapatan Sewa',
    ja: '家賃収入',
    zh: '房屋租金收入'
  },
  'Investments & Dividends': {
    en: 'Investments & Dividends',
    hi: 'निवेश, डिविडेंड व ब्याज',
    hinglish: 'Investment & Mutual Funds',
    ur: 'سرمایہ کاری اور ڈیویڈنڈ',
    bn: 'বিনিয়োগ ও লভ্যাংশ',
    es: 'Inversiones y Dividendos',
    ar: 'الاستثمارات والأرباح',
    fr: 'Investissements & Dividendes',
    de: 'Investitionen & Dividenden',
    ru: 'Инвестиции и дивиденды',
    pt: 'Investimentos e Dividendos',
    id: 'Investasi & Dividen',
    ja: '投資・配当金',
    zh: '投资与股息分红'
  },
  'Bonus & Commissions': {
    en: 'Bonus & Commissions',
    hi: 'बोनस, इंसेंटिव व कमीशन',
    hinglish: 'Bonus & Commission',
    ur: 'بونس اور کمیشن',
    bn: 'বোনাস ও কমিশন',
    es: 'Bonos y Comisiones',
    ar: 'المكافآت والعمولات',
    fr: 'Primes & Commissions',
    de: 'Boni & Provisionen',
    ru: 'Бонусы и комиссии',
    pt: 'Bônus e Comissões',
    id: 'Bonus & Komisi',
    ja: 'ボーナス・歩合給',
    zh: '奖金与佣金提成'
  },
  'Royalties & Digital Products': {
    en: 'Royalties & Digital Products',
    hi: 'रॉयल्टी व डिजिटल उत्पाद आय',
    hinglish: 'Digital Products & Royalties',
    ur: 'رائلٹی اور ڈیجیٹل مصنوعات',
    bn: 'রয়্যালটি ও ডিজিটাল পণ্য',
    es: 'Regalías y Productos Digitales',
    ar: 'العائدات والمنتجات الرقمية',
    fr: 'Royalties & Produits Numériques',
    de: 'Tantiemen & Digitale Produkte',
    ru: 'Роялти и цифровые товары',
    pt: 'Royalties e Produtos Digitais',
    id: 'Royalti & Produk Digital',
    ja: '著作権・デジタル販売',
    zh: '版税与数字产品'
  },
  'Services & Contracts': {
    en: 'Services & Contracts',
    hi: 'सेवा अनुबंध व कॉन्ट्रैक्ट',
    hinglish: 'Services & Contractor Kaam',
    ur: 'سروسز اور معاہدے',
    bn: 'সেবা চুক্তি ও কন্ট্রাক্ট',
    es: 'Servicios y Contratos',
    ar: 'الخدمات والعقود',
    fr: 'Services & Contrats',
    de: 'Dienstleistungen & Verträge',
    ru: 'Услуги и контракты',
    pt: 'Serviços e Contratos',
    id: 'Jasa & Kontrak',
    ja: 'サービス・業務請负',
    zh: '服务与合同结算'
  },
  'General Income': {
    en: 'General Income',
    hi: 'सामान्य आमदनी',
    hinglish: 'General Aamdani',
    ur: 'عام آمدنی',
    bn: 'সাধারণ আয়',
    es: 'Ingreso General',
    ar: 'دخل عام',
    fr: 'Revenu Général',
    de: 'Allgemeine Einnahmen',
    ru: 'Общий доход',
    pt: 'Renda Geral',
    id: 'Pendapatan Umum',
    ja: '一般収入',
    zh: '常规普通收入'
  }
};

export const PAYMENT_MODE_TRANSLATIONS: Record<PaymentMode, Record<AppLanguage, string>> = {
  cash: {
    en: 'Cash in Hand',
    hi: 'नकद (Cash)',
    hinglish: 'Cash Paisa',
    ur: 'نقد رقم (کیش)',
    bn: 'নগদ টাকা',
    es: 'Efectivo',
    ar: 'نقداً (كاش)',
    fr: 'Espèces',
    de: 'Bargeld',
    ru: 'Наличные',
    pt: 'Dinheiro Vivo',
    id: 'Tunai (Cash)',
    ja: '現金',
    zh: '现金支付'
  },
  upi: {
    en: 'UPI / Online / QR',
    hi: 'यूपीआई / ऑनलाइन / क्यूआर',
    hinglish: 'UPI / GPay / PhonePe',
    ur: 'یو پی آئی / آن لائن',
    bn: 'ইউপিআই / অনলাইন',
    es: 'UPI / Pago Digital',
    ar: 'الدفع الإلكتروني (UPI)',
    fr: 'Paiement Sans Contact (UPI)',
    de: 'UPI / Online-Zahlung',
    ru: 'СБП / Онлайн-оплата',
    pt: 'Pix / Online',
    id: 'QRIS / E-Wallet',
    ja: '電子決済・QR',
    zh: '扫码 / 移动支付'
  },
  bank: {
    en: 'Bank Transfer / NEFT',
    hi: 'बैंक ट्रांसफर / नेट बैंकिंग',
    hinglish: 'Bank Transfer / NEFT',
    ur: 'بینک ٹرانسفر',
    bn: 'ব্যাংক ট্রান্সফার',
    es: 'Transferencia Bancaria',
    ar: 'تحويل بنكي',
    fr: 'Virement Bancaire',
    de: 'Banküberweisung',
    ru: 'Банковский перевод',
    pt: 'Transferência Bancária',
    id: 'Transfer Bank',
    ja: '銀行振込',
    zh: '银行转账'
  },
  card: {
    en: 'Debit / Credit Card',
    hi: 'डेबिट / क्रेडिट कार्ड',
    hinglish: 'ATM Card / Credit Card',
    ur: 'ڈیبٹ / کریڈٹ کارڈ',
    bn: 'ডেবিট / ক্রেডিট কার্ড',
    es: 'Tarjeta de Débito/Crédito',
    ar: 'بطاقة ائتمان / مدى',
    fr: 'Carte Bancaire',
    de: 'EC- / Kreditkarte',
    ru: 'Банковская карта',
    pt: 'Cartão de Débito/Crédito',
    id: 'Kartu Debit / Kredit',
    ja: 'クレジットカード / デビット',
    zh: '刷卡 / 信用卡'
  },
  cheque: {
    en: 'Cheque / DD',
    hi: 'चेक / डिमांड ड्राफ्ट',
    hinglish: 'Cheque / Draft',
    ur: 'چیک / ڈرافٹ',
    bn: 'চেক / ড্রাফট',
    es: 'Cheque',
    ar: 'شيك مصرفي',
    fr: 'Chèque',
    de: 'Scheck',
    ru: 'Банковский чек',
    pt: 'Cheque',
    id: 'Cek / Giro',
    ja: '小切手',
    zh: '支票 / 汇票'
  },
  wallet: {
    en: 'Digital Wallet',
    hi: 'डिजिटल वॉलेट',
    hinglish: 'Paytm / Digital Wallet',
    ur: 'ڈیجیٹل والٹ',
    bn: 'ডিজিটাল ওয়ালেট',
    es: 'Billetera Digital',
    ar: 'محفظة إلكترونية',
    fr: 'Portefeuille Électronique',
    de: 'E-Wallet',
    ru: 'Электронный кошелек',
    pt: 'Carteira Digital',
    id: 'Dompet Digital',
    ja: '電子マネー',
    zh: '电子钱包'
  },
  other: {
    en: 'Other Mode',
    hi: 'अन्य भुगतान माध्यम',
    hinglish: 'Other Payment Method',
    ur: 'دیگر طریقہ',
    bn: 'অন্যান্য মাধ্যম',
    es: 'Otro Método',
    ar: 'طريقة أخرى',
    fr: 'Autre Mode',
    de: 'Sonstige Methode',
    ru: 'Другой способ',
    pt: 'Outro Meio',
    id: 'Metode Lain',
    ja: 'その他決済',
    zh: '其他方式'
  }
};

export const WORK_STATUS_TRANSLATIONS: Record<WorkStatus, Record<AppLanguage, string>> = {
  completed: {
    en: 'Completed',
    hi: 'पूर्ण (सम्पन्न)',
    hinglish: 'Complete Ho Gaya',
    ur: 'مکمل ہو گیا',
    bn: 'সম্পূর্ণ হয়েছে',
    es: 'Completado',
    ar: 'مكتمل',
    fr: 'Terminé',
    de: 'Abgeschlossen',
    ru: 'Завершено',
    pt: 'Concluído',
    id: 'Selesai',
    ja: '完了',
    zh: '已完成'
  },
  in_progress: {
    en: 'In Progress',
    hi: 'प्रगति पर (जारी)',
    hinglish: 'Kaam Chalu Hai',
    ur: 'جاری ہے',
    bn: 'চলমান',
    es: 'En Progreso',
    ar: 'قيد التنفيذ',
    fr: 'En cours',
    de: 'In Bearbeitung',
    ru: 'В процессе',
    pt: 'Em Andamento',
    id: 'Sedang Berjalan',
    ja: '進行中',
    zh: '进行中'
  },
  pending: {
    en: 'Pending',
    hi: 'लंबित (प्रतीक्षारत)',
    hinglish: 'Pending Hai',
    ur: 'زیر التواء',
    bn: 'অপেক্ষমাণ',
    es: 'Pendiente',
    ar: 'معلق',
    fr: 'En attente',
    de: 'Ausstehend',
    ru: 'Ожидает',
    pt: 'Pendente',
    id: 'Tertunda',
    ja: '保留中',
    zh: '待处理'
  },
  on_hold: {
    en: 'On Hold',
    hi: 'रोका गया (स्थगित)',
    hinglish: 'Hold Par Hai',
    ur: 'روک دیا گیا',
    bn: 'স্থগিত',
    es: 'En Pausa',
    ar: 'متوقف مؤقتاً',
    fr: 'En pause',
    de: 'Pausiert',
    ru: 'На удержании',
    pt: 'Pausado',
    id: 'Ditahan',
    ja: '中断',
    zh: '已暂停'
  }
};

export const MOOD_TRANSLATIONS: Record<MoodType, Record<AppLanguage, string>> = {
  happy: {
    en: 'Happy & Joyful',
    hi: 'प्रसन्न एवं खुशहाल',
    hinglish: 'Khush & Happy',
    ur: 'خوش و خرم',
    bn: 'আনন্দিত ও প্রফুল্ল',
    es: 'Feliz y Alegre',
    ar: 'سعيد ومبتهج',
    fr: 'Joyeux & Épanoui',
    de: 'Glücklich & Froh',
    ru: 'Счастлив',
    pt: 'Feliz e Radiante',
    id: 'Bahagia & Senang',
    ja: '幸せ・上機嫌',
    zh: '开心快乐'
  },
  productive: {
    en: 'Productive & Focused',
    hi: 'उत्पादक एवं एकाग्र',
    hinglish: 'Productive & Focused',
    ur: 'پُرامید اور محنتی',
    bn: 'উত্পাদনশীল ও মনোযোগী',
    es: 'Productivo y Enfocado',
    ar: 'منتج ومركز',
    fr: 'Productif & Efficace',
    de: 'Produktiv & Fokussiert',
    ru: 'Продуктивно',
    pt: 'Produtivo e Focado',
    id: 'Produktif & Fokus',
    ja: '充実・集中',
    zh: '高效专注'
  },
  normal: {
    en: 'Calm & Balanced',
    hi: 'सामान्य एवं शांत',
    hinglish: 'Normal & Theek',
    ur: 'پرسکون اور معمول پر',
    bn: 'স্বাভাবিক ও শান্ত',
    es: 'Tranquilo y Normal',
    ar: 'هادئ وعادي',
    fr: 'Calme & Serein',
    de: 'Normal & Ruhig',
    ru: 'Спокойно',
    pt: 'Calmo e Equilibrado',
    id: 'Tenang & Santai',
    ja: '普通・穏やか',
    zh: '平稳自然'
  },
  tired: {
    en: 'Tired & Need Rest',
    hi: 'थका हुआ (आराम की जरूरत)',
    hinglish: 'Thaka Hua (Rest Chahiye)',
    ur: 'تھکا ہوا',
    bn: 'ক্লান্ত (বিশ্রাম প্রয়োজন)',
    es: 'Cansado',
    ar: 'متعب وبحاجة للراحة',
    fr: 'Fatigué',
    de: 'Müde & Erschöpft',
    ru: 'Устал',
    pt: 'Cansado',
    id: 'Lelah & Butuh Istirahat',
    ja: 'お疲れ気味',
    zh: '疲惫劳累'
  },
  stressed: {
    en: 'Stressed & Busy',
    hi: 'तनावग्रस्त एवं व्यस्त',
    hinglish: 'Tension & Busy',
    ur: 'پریشان اور مصروف',
    bn: 'মানসিক চাপে',
    es: 'Estresado',
    ar: 'متوتر ومضغوط',
    fr: 'Stressé',
    de: 'Gestresst',
    ru: 'Стресс',
    pt: 'Estressado',
    id: 'Stres & Sibuk',
    ja: 'ストレス過多',
    zh: '压力紧绷'
  },
  blessed: {
    en: 'Blessed & Grateful',
    hi: 'कृतज्ञ एवं धन्यवादी',
    hinglish: 'Shukriya & Blessed',
    ur: 'شکر گزار اور مطمئن',
    bn: 'কৃতজ্ঞ ও ধন্য',
    es: 'Agradecido y Bendecido',
    ar: 'ممتن وشاكر',
    fr: 'Reconnaissant',
    de: 'Dankbar & Gesegnet',
    ru: 'Благодарен',
    pt: 'Grato e Abençoado',
    id: 'Bersyukur & Berkah',
    ja: '感謝・恵まれている',
    zh: '心怀感恩'
  }
};

// ==========================================
// 2. HELPER LOCALIZATION FUNCTIONS
// ==========================================

export function localizeCategory(name: string, lang: AppLanguage | string = 'en'): string {
  if (!name) return '';
  const match = CATEGORY_TRANSLATIONS[name];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return name;
}

export function localizeIncomeSource(name: string, lang: AppLanguage | string = 'en'): string {
  if (!name) return '';
  const match = SOURCE_TRANSLATIONS[name];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return name;
}

export function localizePaymentMode(mode: PaymentMode, lang: AppLanguage | string = 'en'): string {
  const match = PAYMENT_MODE_TRANSLATIONS[mode];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return mode;
}

export function localizeWorkStatus(status: WorkStatus, lang: AppLanguage | string = 'en'): string {
  const match = WORK_STATUS_TRANSLATIONS[status];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return status;
}

export function localizeMood(mood: MoodType, lang: AppLanguage | string = 'en'): string {
  const match = MOOD_TRANSLATIONS[mood];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return mood;
}

// ==========================================
// 3. COMPREHENSIVE UI TEXT DICTIONARIES
// ==========================================

export const TRACKER_TRANSLATIONS: Record<string, Record<AppLanguage, string>> = {
  headerTitle: {
    en: 'Work Deliverables & Daily Life Tracker',
    hi: 'काम व दैनिक जीवन ट्रैकर',
    hinglish: 'Work Deliverables & Daily Life Tracker',
    ur: 'کام اور روزمرہ زندگی ٹریکر',
    bn: 'কর্ম ও দৈনন্দিন জীবন ট্র্যাকার',
    es: 'Registro de Trabajo y Vida Diaria',
    ar: 'متتبع العمل واليوميات',
    fr: 'Suivi du Travail et du Quotidien',
    de: 'Arbeits- & Lebenstagebuch',
    ru: 'Трекер работы и личной жизни',
    pt: 'Rastreador de Trabalho e Rotina',
    id: 'Pelacak Kerja & Jurnal Harian',
    ja: '仕事・日常トラッカー',
    zh: '工作产出与生活日志'
  },
  headerSubtitle: {
    en: 'Universal logbook for client projects, deliverables, daily routines and journal highlights.',
    hi: 'काम का इतिहास, ग्राहक डिलीवरेबल्स और दैनिक जीवन डायरी को सुरक्षित रूप से ट्रैक करें।',
    hinglish: 'Client projects, daily routines aur journal highlights ko organize karein.',
    ur: 'کلائنٹ پروجیکٹس، روزمرہ معمولات اور ڈائری کو محفوظ طریقے سے ٹریک کریں۔',
    bn: 'ক্লায়েন্ট প্রজেক্ট, কাজের হিসাব এবং দৈনন্দিন জীবনের গুরুত্বপূর্ণ মুহূর্তগুলো লিখে রাখুন।',
    es: 'Libro de registro universal para proyectos, entregas de clientes y rutinas diarias.',
    ar: 'سجل شامل لمشاريع العملاء وساعات العمل المنجزة وعادات اليوميات.',
    fr: 'Journal de bord pour vos projets, livrables clients et habitudes quotidiennes.',
    de: 'Universelles Tagebuch für Kundenprojekte, Ergebnisse und Tagesabläufe.',
    ru: 'Универсальный журнал для клиентских проектов, задач и ежедневных заметок.',
    pt: 'Diário de bordo para projetos, entregas de clientes e rotinas diárias.',
    id: 'Buku catatan serbaguna untuk proyek klien, rutinitas, dan catatan penting.',
    ja: 'クライアント案件、成果物、日課、日記を一括管理。',
    zh: '客户项目、工作交付、日常习惯与心得体会统一记录。'
  },
  logWorkBtn: {
    en: '+ Log Work',
    hi: '+ काम जोड़ें',
    hinglish: '+ Work Add Karein',
    ur: '+ کام درج کریں',
    bn: '+ কাজ যুক্ত করুন',
    es: '+ Registrar Trabajo',
    ar: '+ تسجيل عمل',
    fr: '+ Ajouter Travail',
    de: '+ Arbeit erfassen',
    ru: '+ Добавить работу',
    pt: '+ Registrar Trabalho',
    id: '+ Catat Kerja',
    ja: '+ 仕事を記録',
    zh: '+ 记录工作'
  },
  todayStoryBtn: {
    en: "+ Today's Story",
    hi: '+ आज की डायरी',
    hinglish: "+ Aaj ki Diary",
    ur: '+ آج کی ڈائری',
    bn: '+ আজকের গল্প',
    es: '+ Diario de Hoy',
    ar: '+ يوميات اليوم',
    fr: '+ Journal du Jour',
    de: '+ Heutiger Eintrag',
    ru: '+ Заметка за день',
    pt: '+ Diário de Hoje',
    id: '+ Cerita Hari Ini',
    ja: '+ 今日の日記',
    zh: '+ 今日日志'
  },
  totalWorkItems: {
    en: 'Total Work Items',
    hi: 'कुल कार्य',
    hinglish: 'Total Work Items',
    ur: 'کل کام',
    bn: 'মোট কাজের সংখ্যা',
    es: 'Total de Trabajos',
    ar: 'إجمالي الأعمال',
    fr: 'Total des Tâches',
    de: 'Gesamte Aufgaben',
    ru: 'Всего задач',
    pt: 'Total de Tarefas',
    id: 'Total Pekerjaan',
    ja: '総作業項目',
    zh: '总工作项'
  },
  loggedHours: {
    en: 'Logged Hours',
    hi: 'कुल समय',
    hinglish: 'Logged Hours',
    ur: 'ریکارڈ شدہ گھنٹے',
    bn: 'মোট সময় (ঘণ্টা)',
    es: 'Horas Registradas',
    ar: 'الساعات المسجلة',
    fr: 'Heures Enregistrées',
    de: 'Erfasste Stunden',
    ru: 'Отработано часов',
    pt: 'Horas Registradas',
    id: 'Jam Tercatat',
    ja: '記録時間',
    zh: '已记工时'
  },
  workRevenue: {
    en: 'Work Revenue / Billables',
    hi: 'कार्य आय / शुल्क',
    hinglish: 'Work Revenue / Kamai',
    ur: 'کام کی آمدنی',
    bn: 'কাজের আয় / বিলিং',
    es: 'Ingresos Facturables',
    ar: 'إيرادات الأعمال المفوترة',
    fr: 'Revenus Facturables',
    de: 'Umsatz / Abrechenbar',
    ru: 'Доход от проектов',
    pt: 'Faturamento de Projetos',
    id: 'Pendapatan Proyek',
    ja: '請求可能額',
    zh: '工作应收 / 营收'
  },
  lifeJournalDays: {
    en: 'Life Journal Days',
    hi: 'दैनिक डायरी प्रविष्टियाँ',
    hinglish: 'Life Journal Days',
    ur: 'ڈائری کے دن',
    bn: 'ডায়েরির দিনলিপি',
    es: 'Días de Diario',
    ar: 'أيام اليوميات',
    fr: 'Jours de Journal',
    de: 'Tagebucheinträge',
    ru: 'Дней в дневнике',
    pt: 'Dias de Diário',
    id: 'Hari Jurnal',
    ja: '日記記録日数',
    zh: '日志记录天数'
  },
  workTab: {
    en: 'Work Deliverables',
    hi: 'कार्य डिलीवरेबल्स',
    hinglish: 'Work Deliverables',
    ur: 'پروجیکٹس اور کام',
    bn: 'কাজের হিসাব',
    es: 'Entregables de Trabajo',
    ar: 'مخرجات العمل',
    fr: 'Livrables de Travail',
    de: 'Arbeitsergebnisse',
    ru: 'Рабочие задачи',
    pt: 'Entregáveis de Trabalho',
    id: 'Hasil Kerja',
    ja: '仕事の成果物',
    zh: '工作交付项'
  },
  lifeTab: {
    en: 'Daily Life Stories',
    hi: 'दैनिक जीवन डायरी',
    hinglish: 'Daily Life Stories',
    ur: 'روزمرہ ڈائری',
    bn: 'দৈনন্দিন জীবনের ডায়েরি',
    es: 'Historias del Día',
    ar: 'قصص اليوميات',
    fr: 'Histoires du Quotidien',
    de: 'Tagesgeschichten',
    ru: 'Заметки о жизни',
    pt: 'Histórias do Dia a Dia',
    id: 'Cerita Kehidupan Sehari-hari',
    ja: '日々のストーリー',
    zh: '生活点滴与反思'
  }
};

export const NOTES_TRANSLATIONS: Record<string, Record<AppLanguage, string>> = {
  vaultBadge: {
    en: 'Private Personal Vault',
    hi: '100% प्राइवेट व सेपरेट वॉल्ट',
    hinglish: '100% Private Vault',
    ur: '100% نجی والٹ',
    bn: '১০০% ব্যক্তিগত সুরক্ষিত ভল্ট',
    es: 'Bóveda Personal Privada',
    ar: 'خزنة شخصية خاصة 100%',
    fr: 'Coffre-Fort Privé',
    de: 'Privater Safe',
    ru: 'Личный сейф заметок',
    pt: 'Cofre Pessoal Privado',
    id: 'Brankas Catatan Pribadi',
    ja: '個人用プライベート金庫',
    zh: '个人专属私密备忘库'
  },
  vaultTitle: {
    en: 'Personal Notes & Private Memos',
    hi: 'पर्सनल नोट्स एवं सीक्रेट डायरी',
    hinglish: 'Personal Notes & Secret Diary',
    ur: 'پرسنل نوٹس اور نجی ڈائری',
    bn: 'ব্যক্তিগত নোট ও গোপন ডায়েরি',
    es: 'Notas Personales y Memos Privados',
    ar: 'الملاحظات الشخصية والمذكرات السرية',
    fr: 'Notes Personnelles & Mémos Privés',
    de: 'Persönliche Notizen & Memos',
    ru: 'Личные заметки и мысли',
    pt: 'Notas Pessoais e Memórias',
    id: 'Catatan Pribadi & Memo Rahasia',
    ja: 'パーソナルノート・非公開メモ',
    zh: '个人备忘与私密笔记'
  },
  vaultSubtitle: {
    en: 'A dedicated private space isolated from records and finances. Keep your personal reflections, passwords hints, ideas, and checklists 100% offline in your browser.',
    hi: 'खाता और खर्चों से बिल्कुल अलग अपना पर्सनल स्पेस। यहाँ अपने गुप्त विचार, जरूरी क्रेडेंशियल्स, पासवर्ड हिंट्स, टू-डू लिस्ट और मेमो 100% सुरक्षित और ऑफलाइन रखें।',
    hinglish: 'Record se alag aapka personal space. Apne private ideas, passwords hints aur checklist offline safe rakhein.',
    ur: 'کھاتہ اور حساب کتاب سے الگ ایک نجی گوشہ۔ اپنے خفیہ خیالات، پاس ورڈ کے اشارے اور نوٹس مکمل آف لائن محفوظ رکھیں۔',
    bn: 'হিসাব খাতা থেকে আলাদা আপনার একান্ত ব্যক্তিগত জায়গা। পাসওয়ার্ড হিন্টস, টু-ডু লিস্ট ও গুরুত্বপূর্ণ চিন্তা নিরাপদে রাখুন।',
    es: 'Un espacio privado aislado de finanzas. Guarde reflexiones, contraseñas, ideas y listas 100% fuera de línea en su navegador.',
    ar: 'مساحة خاصة معزولة تماماً عن الحسابات المالية لحفظ أفكارك وتلميحات كلمات المرور وقوائم المهام بدون إنترنت.',
    fr: 'Un espace privé isolé des finances. Conservez vos réflexions, indices de mot de passe et listes 100% hors ligne.',
    de: 'Ein privater Bereich getrennt von Finanzen. Bewahren Sie Passwörter, Gedanken und Checklisten offline auf.',
    ru: 'Личное пространство отдельно от бухгалтерии. Храните подсказки паролей, идеи и списки дел офлайн.',
    pt: 'Um espaço privado isolado das finanças para guardar ideias, dicas de senhas e tarefas 100% offline.',
    id: 'Ruang privat terpisah dari pembukuan untuk menyimpan ide rahasia, pengingat, dan daftar tugas secara offline.',
    ja: '家計簿から独立した完全プライベート空間。パスワードのヒント、アイデア、ToDoリストをオフラインで安全に保管。',
    zh: '独立于日常账本的纯私密空间。在浏览器本地离线安全存放私人灵感、密码提示、随笔与待办清单。'
  },
  createNoteBtn: {
    en: 'Create Note',
    hi: 'नया नोट लिखें',
    hinglish: 'Note Banayein',
    ur: 'نیا نوٹ لکھیں',
    bn: 'নতুন নোট তৈরি করুন',
    es: 'Crear Nota',
    ar: 'إنشاء ملاحظة',
    fr: 'Créer une Note',
    de: 'Notiz erstellen',
    ru: 'Создать заметку',
    pt: 'Criar Nota',
    id: 'Buat Catatan',
    ja: 'ノート作成',
    zh: '新建笔记'
  },
  totalNotes: {
    en: 'Total Notes',
    hi: 'कुल नोट्स',
    hinglish: 'Total Notes',
    ur: 'کل نوٹس',
    bn: 'মোট নোট',
    es: 'Total de Notas',
    ar: 'إجمالي الملاحظات',
    fr: 'Total des Notes',
    de: 'Alle Notizen',
    ru: 'Всего заметок',
    pt: 'Total de Notas',
    id: 'Total Catatan',
    ja: '総ノート数',
    zh: '笔记总数'
  },
  pinnedNotes: {
    en: 'Pinned',
    hi: 'पिन किए गए',
    hinglish: 'Pinned',
    ur: 'پن شدہ',
    bn: 'পিন করা',
    es: 'Fijadas',
    ar: 'المثبتة',
    fr: 'Épinglées',
    de: 'Angeheftet',
    ru: 'Закрепленные',
    pt: 'Fixadas',
    id: 'Disematkan',
    ja: 'ピン留め',
    zh: '已置顶'
  },
  secretNotes: {
    en: 'Secret / Masked',
    hi: 'मास्क्ड / सीक्रेट',
    hinglish: 'Secret / Masked',
    ur: 'خفیہ / ماسکڈ',
    bn: 'গোপন / মাস্কড',
    es: 'Secretas / Ocultas',
    ar: 'سرية / مخفية',
    fr: 'Secrètes / Masquées',
    de: 'Geheim / Maskiert',
    ru: 'Секретные',
    pt: 'Secretas / Ocultas',
    id: 'Rahasia / Tersembunyi',
    ja: '非公開・暗号化',
    zh: '私密 / 遮蔽'
  },
  quickMemoPrompt: {
    en: 'Write a quick personal note / scratchpad here...',
    hi: 'त्वरित पर्सनल नोट लिखें (क्लिक करें)...',
    hinglish: 'Quick personal note likhein (click karein)...',
    ur: 'فوری نجی نوٹ درج کریں...',
    bn: 'দ্রুত ব্যক্তিগত নোট লিখুন (ক্লিক করুন)...',
    es: 'Escriba una nota rápida aquí...',
    ar: 'اكتب ملاحظة سريعة هنا...',
    fr: 'Écrire un mémo rapide ici...',
    de: 'Schnellnotiz hier verfassen...',
    ru: 'Быстрая заметка (нажмите здесь)...',
    pt: 'Escreva uma nota rápida aqui...',
    id: 'Tulis memo cepat di sini...',
    ja: 'ここにクイックメモを入力...',
    zh: '点击此处快速记录个人便签...'
  },
  searchPlaceholder: {
    en: 'Search in notes (title, body or #tags)...',
    hi: 'नोट्स में खोजें (शीर्षक, शब्द या #टैग)...',
    hinglish: 'Notes mein search karein (title, body ya #tags)...',
    ur: 'نوٹس میں تلاش کریں (عنوان، متن یا #ٹیگ)...',
    bn: 'নোট খুঁজুন (শিরোনাম, বিবরণ বা #ট্যাগ)...',
    es: 'Buscar en notas (título, contenido o #etiquetas)...',
    ar: 'البحث في الملاحظات (العنوان، المحتوى أو الوسوم)...',
    fr: 'Rechercher dans les notes (titre, texte ou #tags)...',
    de: 'In Notizen suchen (Titel, Text oder #Tags)...',
    ru: 'Поиск по заметкам (заголовок, текст, #теги)...',
    pt: 'Buscar em notas (título, conteúdo ou #tags)...',
    id: 'Cari di catatan (judul, isi, atau #tag)...',
    ja: 'ノートを検索（タイトル、本文、#タグ）...',
    zh: '在笔记中搜索（标题、正文或#标签）...'
  },
  allNotes: {
    en: 'All Notes',
    hi: 'सभी नोट्स',
    hinglish: 'All Notes',
    ur: 'تمام نوٹس',
    bn: 'সব নোট',
    es: 'Todas las Notas',
    ar: 'جميع الملاحظات',
    fr: 'Toutes les Notes',
    de: 'Alle Notizen',
    ru: 'Все заметки',
    pt: 'Todas as Notas',
    id: 'Semua Catatan',
    ja: 'すべてのノート',
    zh: '全部笔记'
  },
  secretVault: {
    en: 'Secret Vault',
    hi: 'गोपनीय / सीक्रेट',
    hinglish: 'Secret Vault',
    ur: 'خفیہ تجوری',
    bn: 'গোপন ভল্ট',
    es: 'Bóveda Secreta',
    ar: 'الخزنة السرية',
    fr: 'Coffre Secret',
    de: 'Geheimer Tresor',
    ru: 'Секретный сейф',
    pt: 'Cofre Secreto',
    id: 'Brankas Rahasia',
    ja: 'シークレット金庫',
    zh: '私密保险库'
  },
  emptyVault: {
    en: 'Your Personal Notes Vault is Empty',
    hi: 'कोई पर्सनल नोट मौजूद नहीं है',
    hinglish: 'Koi personal note nahi hai',
    ur: 'آپ کی نجی ڈائری خالی ہے',
    bn: 'কোনো ব্যক্তিগত নোট নেই',
    es: 'Su bóveda de notas está vacía',
    ar: 'خزنة الملاحظات الشخصية فارغة',
    fr: 'Votre carnet de notes est vide',
    de: 'Ihr Notiztresor ist leer',
    ru: 'Ваш сейф заметок пуст',
    pt: 'Seu cofre de notas está vazio',
    id: 'Brankas catatan Anda kosong',
    ja: 'ノートがまだありません',
    zh: '个人私密笔记库暂无内容'
  },
  emptyVaultDesc: {
    en: 'Start jotting down private thoughts, project ideas, to-do checklists, or secret credentials.',
    hi: 'अपने व्यक्तिगत विचार, गुप्त पासवर्ड्स, जरूरी टू-डू लिस्ट या महत्वपूर्ण मेमो यहाँ सुरक्षित रखें।',
    hinglish: 'Apne personal thoughts, secret passwords hints ya to-do list yahan save karein.',
    ur: 'اپنے ذاتی خیالات، اہم پاس ورڈز، فہرستیں اور یادداشتیں یہاں محفوظ کریں۔',
    bn: 'ব্যক্তিগত ভাবনা, গোপন পাসওয়ার্ড হিন্ট বা টু-ডু তালিকা এখানে সুরক্ষিত রাখুন।',
    es: 'Anote pensamientos privados, ideas, contraseñas o listas de verificación.',
    ar: 'ابدأ بتدوين أفكارك الخاصة، وتلميحات كلمات المرور وقوائم المهام بكل أمان.',
    fr: 'Consignez vos pensées privées, idées, listes ou identifiants en sécurité.',
    de: 'Erfassen Sie private Gedanken, Ideen, To-Do-Listen oder vertrauliche Notizen.',
    ru: 'Записывайте личные мысли, идеи, списки дел и подсказки к паролям.',
    pt: 'Anote reflexões pessoais, ideias, tarefas e credenciais seguras.',
    id: 'Mulai tulis pemikiran pribadi, ide, daftar to-do, atau pengingat penting.',
    ja: '個人のアイデア、ToDoリスト、秘密のメモを安全に書き留めましょう。',
    zh: '开始记录私人想法、项目灵感、待办清单或安全密码提示。'
  },
  createFirstNote: {
    en: 'Create First Note',
    hi: 'पहला नोट लिखें',
    hinglish: 'Pehla Note Banayein',
    ur: 'پہلا نوٹ بنائیں',
    bn: 'প্রথম নোট তৈরি করুন',
    es: 'Crear Primera Nota',
    ar: 'إنشاء أول ملاحظة',
    fr: 'Créer une première note',
    de: 'Erste Notiz anlegen',
    ru: 'Создать первую заметку',
    pt: 'Criar Primeira Nota',
    id: 'Buat Catatan Pertama',
    ja: '最初のノートを作成',
    zh: '创建第一条笔记'
  },
  secretNoteClick: {
    en: 'Secret Note: Click to View',
    hi: 'सीक्रेट नोट: देखने के लिए क्लिक करें',
    hinglish: 'Secret Note: Dekhne ke liye click karein',
    ur: 'خفیہ نوٹ: دیکھنے کے لیے کلک کریں',
    bn: 'গোপন নোট: দেখতে ক্লিক করুন',
    es: 'Nota secreta: clic para ver',
    ar: 'ملاحظة سرية: انقر للعرض',
    fr: 'Note secrète : cliquer pour afficher',
    de: 'Geheimnotiz: Zum Anzeigen klicken',
    ru: 'Секретная заметка: нажмите для просмотра',
    pt: 'Nota secreta: clique para ver',
    id: 'Catatan rahasia: klik untuk melihat',
    ja: '暗号化メモ：クリックして表示',
    zh: '私密笔记：点击查看内容'
  },
  hiddenForPrivacy: {
    en: 'Hidden for privacy',
    hi: 'गोपनीयता के लिए मास्क्ड',
    hinglish: 'Privacy ke liye hidden',
    ur: 'رازداری کے لیے پوشیدہ',
    bn: 'গোপনীয়তার জন্য লুকানো',
    es: 'Oculto por privacidad',
    ar: 'مخفي للخصوصية',
    fr: 'Masqué pour la confidentialité',
    de: 'Aus Datenschutzgründen verborgen',
    ru: 'Скрыто для конфиденциальности',
    pt: 'Oculto por privacidade',
    id: 'Disembunyikan demi privasi',
    ja: 'プライバシー保護のため非表示',
    zh: '因隐私保护已遮蔽'
  },
  saveNoteBtn: {
    en: 'Save Note',
    hi: 'सहेजें',
    hinglish: 'Save Karein',
    ur: 'محفوظ کریں',
    bn: 'সংরক্ষণ করুন',
    es: 'Guardar Nota',
    ar: 'حفظ الملاحظة',
    fr: 'Enregistrer',
    de: 'Notiz speichern',
    ru: 'Сохранить',
    pt: 'Salvar Nota',
    id: 'Simpan Catatan',
    ja: '保存する',
    zh: '保存笔记'
  },
  cancelBtn: {
    en: 'Cancel',
    hi: 'रद्द करें',
    hinglish: 'Cancel Karein',
    ur: 'منسوخ کریں',
    bn: 'বাতিল',
    es: 'Cancelar',
    ar: 'إلغاء',
    fr: 'Annuler',
    de: 'Abbrechen',
    ru: 'Отмена',
    pt: 'Cancelar',
    id: 'Batal',
    ja: 'キャンセル',
    zh: '取消'
  }
};

export function getTrackerText(key: keyof typeof TRACKER_TRANSLATIONS, lang: AppLanguage | string = 'en'): string {
  const match = TRACKER_TRANSLATIONS[key];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return TRACKER_TRANSLATIONS[key]?.en || '';
}

export function getNotesText(key: keyof typeof NOTES_TRANSLATIONS, lang: AppLanguage | string = 'en'): string {
  const match = NOTES_TRANSLATIONS[key];
  if (match && (match as any)[lang]) return (match as any)[lang];
  return NOTES_TRANSLATIONS[key]?.en || '';
}

